[dev]
  command = "npm run dev"
  framework = "gridsome"

[build]
  publish = "dist"
  command = "npm run build"
  functions = "api/"

[[redirects]]
  from = "api/*"
  to = ".netlify/functions/:splat"
  status = 200
